# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      # specify the version
      - image: liamg/golang-opengl
    working_directory: /go/src/github.com/liamg/aminal
    steps:
      - checkout
      - run: make test
  build-linux:
    docker:
      # specify the version
      - image: liamg/golang-opengl
    working_directory: /go/src/github.com/liamg/aminal
    requires:
      - build
    steps:
      - checkout
      - run: make build-linux
      - run: tree bin
  build-darwin:
    docker:
      # specify the version
      - image: karalabe/xgo-latest:latest
    working_directory: /go/src/github.com/liamg/aminal
    steps:
      - checkout
      - run: make build-darwin
      - run: tree bin
  release:
    docker:
      # specify the version
      - image: karalabe/xgo-latest:latest
    working_directory: /go/src/github.com/liamg/aminal
    steps:
      - checkout
      - run: echo nothing to do
workflows:
  version: 2
  build:
    jobs:
      - test
      - build-darwin:
          requires:
            - test
      - build-linux:
          requires:
            - test
      - release:
          requires:
            - build-linux
            - build-darwin
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/