# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: liamg/golang-opengl
    working_directory: /go/src/github.com/liamg/aminal
    steps:
      - checkout
      - run: make test
  release:
    docker:
      # specify the version
      - image: liamg/golang-opengl
    requires:
      - build
    steps:
      - checkout
      - run: make release
    filters:
      tags:
        only: /.*/
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release